### ISSUE TITLE
Can it be plugged directly into an Arduino like a HC-SR04?

### ISSUE THREAD

**Issue by taitems** [ritesht93/waterproof_small_blind_ultrasonic_sensor_DYP-A02YYxx_v1.0#1]
As the title says, can this be connected directly to a breadboard/Arduino without the need for any extra parts, just like a HC-SR04? I ask because other waterproof components like the JSN-SR04T seem to plug into a separate board first. 

JSN-SR04T pictured below:
![image](https://user-images.githubusercontent.com/234593/57130288-53f04a00-6ddc-11e9-8fd4-f7db8036ac9f.png)

Thanks.

**Comment by riteshRcH** [comment]
Hello there,

Apologies for the late reply. I was out of my home country for a couple of weeks regarding electronic conferences. 

The answer to your question is: Yes.

It can be directly connected to an arduino just like HC-SR04. In JSN-SR04T, PCB board and transducer are separate.

In this sensor, PCB board and transducer are together, both of them sealed from all sides making it waterproof. From the PCB board a separate wire comes out with a connector so that you can connect it directly to arduino or raspberry pi or any other board.

Please see attached photo below showing the cable with connectors for arduino at the end:

![image](https://user-images.githubusercontent.com/11679109/59175955-1a49f600-8b75-11e9-8ec3-2317182c1159.png)


Thanks

**Comment by ritesht93** [comment]
Resolved.
